# Generated by Django 4.2.3 on 2023-07-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0002_alter_user_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oranization',
            name='org_lang',
        ),
    ]
