# Generated by Django 4.2.3 on 2023-07-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0003_remove_oranization_org_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='safe_connected.oranization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safe_connected.user_lang'),
        ),
    ]
