# Generated by Django 4.2.3 on 2023-07-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0004_remove_event_location_event_city_event_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='safe_connected.lang'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='safe_connected.eventtype'),
        ),
    ]
