# Generated by Django 4.2.3 on 2023-07-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0005_alter_user_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oranization',
            new_name='Organization',
        ),
    ]
