# Generated by Django 4.2.3 on 2023-07-18 22:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0006_eventroster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
