# Generated by Django 4.2.3 on 2023-07-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0007_alter_organizationprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='org_notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Manager', 'Manager')], default='Client', max_length=10),
        ),
    ]
