# Generated by Django 4.2.3 on 2023-07-19 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0010_eventroster_event_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='safe_connected.organizationprofile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_organizer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
