# Generated by Django 4.2.3 on 2023-07-19 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0010_eventroster_event_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventroster',
            name='event_manager',
        ),
        migrations.AlterField(
            model_name='eventroster',
            name='client_attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
