# Generated by Django 4.2.3 on 2023-07-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0012_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_desc',
            field=models.CharField(default='avatar', max_length=50),
            preserve_default=False,
        ),
    ]
