# Generated by Django 4.2.3 on 2023-07-20 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0013_fileupload_file_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventroster',
            name='client_attendee',
        ),
        migrations.RemoveField(
            model_name='eventroster',
            name='event_organization',
        ),
        migrations.AddField(
            model_name='eventroster',
            name='attendee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
