# Generated by Django 4.2.3 on 2023-07-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0013_fileupload_file_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Manager', 'Manager')], max_length=10),
        ),
    ]
