# Generated by Django 4.2.3 on 2023-07-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0014_alter_user_role'),
        ('safe_connected', '0015_remove_eventroster_client_attendee_and_more'),
    ]

    operations = [
    ]
