# Generated by Django 4.2.3 on 2023-07-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0018_alter_organizationmembership_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationmembership',
            old_name='client',
            new_name='member',
        ),
    ]
