# Generated by Django 4.2.3 on 2023-07-23 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0020_clientlanguagemembership_is_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_attendees',
            field=models.ManyToManyField(related_name='attended_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
