# Generated by Django 4.2.3 on 2023-07-24 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0023_alter_event_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organiz_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
