# Generated by Django 4.2.3 on 2023-07-24 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0024_alter_organizationmembership_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
