# Generated by Django 4.2.3 on 2023-07-25 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0025_alter_event_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
