# Generated by Django 4.2.3 on 2023-07-25 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0026_event_event_date_event_event_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_start_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
