# Generated by Django 4.2.3 on 2023-07-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0028_event_event_title_es_event_event_title_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_title_en_us',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='general_notes_en_us',
            field=models.TextField(null=True),
        ),
    ]
