# Generated by Django 4.2.3 on 2023-07-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0029_event_event_title_en_us_event_general_notes_en_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_language',
            field=models.CharField(choices=[('es', 'es'), ('fr', 'fr'), ('sw', 'sw')], max_length=5),
        ),
    ]
