# Generated by Django 4.2.3 on 2023-07-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0030_alter_event_event_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_title_sw',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='general_notes_sw',
            field=models.TextField(null=True),
        ),
    ]
