# Generated by Django 4.2.3 on 2023-07-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0031_event_event_title_sw_event_general_notes_sw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Manager', 'Manager')], default='Client', max_length=10),
        ),
    ]
