# Generated by Django 4.2.3 on 2023-07-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0033_remove_event_event_language_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='org_avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
