# Generated by Django 4.2.3 on 2023-07-29 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0034_event_event_avatar_organizationprofile_org_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='client_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
