# Generated by Django 4.2.3 on 2023-07-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0035_alter_fileupload_client_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='org_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
