# Generated by Django 4.2.3 on 2023-07-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0036_event_event_published_alter_event_event_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_published',
            field=models.BooleanField(default=False),
        ),
    ]
