# Generated by Django 4.2.3 on 2023-07-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0036_event_event_published_alter_event_event_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('es', 'es'), ('fr', 'fr'), ('sw', 'sw'), ('en', 'en')], max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Manager', 'Manager')], max_length=10),
        ),
    ]
