# Generated by Django 4.2.3 on 2023-07-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0037_alter_user_language_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
