# Generated by Django 4.2.3 on 2023-08-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_connected', '0038_alter_user_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='client',
        ),
        migrations.RemoveField(
            model_name='managerorgmembership',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='managerorgmembership',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='orglanguagemembership',
            name='org_language',
        ),
        migrations.RemoveField(
            model_name='orglanguagemembership',
            name='organization',
        ),
        migrations.DeleteModel(
            name='ClientLanguageMembership',
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.DeleteModel(
            name='Lang',
        ),
        migrations.DeleteModel(
            name='ManagerOrgMembership',
        ),
        migrations.DeleteModel(
            name='OrgLanguageMembership',
        ),
    ]
